import { useState } from 'react'
import { rpc } from './api'
import type { Attempt, Material, Reference } from './types'
import { EmptyState } from './ui'
type Run = (action: () => Promise<void>) => Promise<void>
function SourceRef({ reference, material }: { reference: Reference; material: Material }) {
  if (!reference || reference.status === 'unverified') return <p className="lp-muted" role="status">ไม่สามารถยืนยันแหล่งอ้างอิงได้ · ไม่พบหลักฐานที่ตรงกัน</p>
  const section = material.source.slice(reference.start ?? (reference.section - 1) * 2000, reference.end ?? reference.section * 2000)
  return <details className="lp-reference"><summary>↗ อ้างอิงส่วนที่ {reference.section}{reference.end_section && reference.end_section !== reference.section ? `–${reference.end_section}` : ''}{reference.page ? ` · หน้า ${reference.page}` : ''}</summary><blockquote>{reference.excerpt}</blockquote><p className="lp-source">{section}</p></details>
}
export default function Quiz({ attempt: a, material, busy, online, run, refresh, onBack, onPlan, onProgress, report }: { attempt: Attempt; material: Material; busy: boolean; online: boolean; run: Run; refresh: () => Promise<void>; onBack: () => void; onPlan: () => void; onProgress: () => void; report: (id: string, s: string) => Promise<void> }) {
  const [answers, setAnswers] = useState(a.answers)
  const [index, setIndex] = useState(0)
  const [saved, setSaved] = useState('')
  const q = a.questions[index]
  const select = (answer: number) => {
    const next = { ...answers, [q.id]: answer }; setAnswers(next); setSaved('ยังไม่ได้บันทึก')
    void run(async () => { await rpc('lp_save_draft', { p_attempt: a.id, p_answers: next }); setSaved('บันทึกคำตอบแล้ว'); await refresh() })
  }
  if (a.result) return <><button className="lp-link" onClick={onBack}>← กลับสรุป</button><div className="lp-heading"><div><span className="lp-eyebrow">QUIZ RESULTS</span><h1>ผลทดสอบความเข้าใจ</h1><p>ดูสิ่งที่เข้าใจ แล้วค่อยกลับไปทบทวนสิ่งที่ยังไม่มั่นใจ</p></div></div><div className="lp-card lp-result">{a.result.notice && <div className="lp-alert">{a.result.notice} ({a.result.withdrawn_count} ข้อ)</div>}<strong>{a.result.score}<small> / {a.result.total}</small></strong><p>ตอบถูก {a.result.score} จาก {a.result.total} ข้อ</p><p>ดูหลักฐานราย concept ในหน้าความก้าวหน้า และแผนใหม่ในหน้าแผนเรียน</p></div><div className="lp-result-actions"><button onClick={onPlan}>ดูแผนทบทวน →</button><button className="lp-secondary" onClick={onProgress}>ดูความเข้าใจรายหัวข้อ</button></div>{a.result.feedback.map((f, i) => <article className={`lp-card lp-feedback-card ${f.selected === f.correct ? '' : 'needs-review'}`} key={f.question_id}><span className={`lp-tag ${f.selected === f.correct ? '' : 'danger'}`}>{f.selected === f.correct ? 'ถูกต้อง' : 'ควรทบทวน'}</span><h3>{i + 1}. {f.prompt}</h3><div className="lp-answer-review"><p>คำตอบของคุณ: {f.choices[f.selected]}</p><p><strong>คำตอบที่ถูก: {f.choices[f.correct]}</strong></p></div><p>{f.explanation}</p><SourceRef reference={f.reference} material={material} /><IssueForm busy={busy || !online} onReport={s => void report(f.question_id, s)} /></article>)}</>
  if (!q) return <EmptyState title="ยังไม่มีคำถามในชุดนี้" text="กลับไปบทเรียนแล้วสร้างแบบทดสอบใหม่" action={<button onClick={onBack}>กลับไปบทเรียน</button>} />
  return <><button className="lp-link" disabled={busy} onClick={onBack}>← กลับบทเรียน · เก็บคำตอบที่บันทึกแล้ว</button><div className="lp-heading"><div><span className="lp-eyebrow">CHECK YOUR UNDERSTANDING</span><h1>ทดสอบความเข้าใจ</h1><p>เฉลยจะแสดงหลังส่งครบทุกข้อ · {a.questions.length < 10 && `มีคำถามใหม่เพียง ${a.questions.length} ข้อจากเนื้อหานี้`}</p></div><span className="lp-tag info">ข้อ {index + 1} / {a.questions.length}</span></div><p className="lp-quiz-completion" role="status">ตอบแล้ว {Object.keys(answers).length} จาก {a.questions.length} ข้อ</p><progress max={a.questions.length} value={Object.keys(answers).length} aria-label="จำนวนข้อที่ตอบแล้ว" /><section className="lp-card lp-question" key={q.id}><span className="lp-tag">ข้อที่ {index + 1}</span><h2>{q.prompt}</h2><fieldset><legend className="lp-sr">เลือกหนึ่งคำตอบ</legend>{q.choices.map((choice, i) => <label className={`lp-choice ${answers[q.id] === i ? 'selected' : ''}`} key={i}><input type="radio" name={q.id} checked={answers[q.id] === i} disabled={busy || !online} onChange={() => select(i)} /><span>{String.fromCharCode(65 + i)}.</span>{choice}</label>)}</fieldset><p role="status" className="lp-muted">{saved || 'คำตอบที่บันทึกแล้วสามารถกลับมาทำต่อได้'}</p><div className="lp-row"><button className="lp-secondary" disabled={index === 0 || busy} onClick={() => setIndex(index - 1)}>← ก่อนหน้า</button><button className="lp-secondary" disabled={index === a.questions.length - 1 || busy} onClick={() => setIndex(index + 1)}>ถัดไป →</button></div></section><div className="lp-actions lp-quiz-numbers">{a.questions.map((question, i) => <button className={answers[question.id] === undefined ? 'lp-secondary' : ''} key={question.id} aria-current={index === i ? 'step' : undefined} aria-label={`ไปข้อ ${i + 1}${answers[question.id] === undefined ? ' ยังไม่ได้ตอบ' : ' ตอบแล้ว'}`} onClick={() => setIndex(i)} disabled={busy}>{i + 1}</button>)}</div><button className="lp-submit" disabled={busy || !online || Object.keys(answers).length !== a.questions.length} onClick={() => void run(async () => { await rpc('lp_submit_quiz', { p_attempt: a.id, p_answers: answers }); await refresh() })}>ส่งคำตอบและปรับแผน →</button></>
}
function IssueForm({ busy, onReport }: { busy: boolean; onReport: (s: string) => void }) {
  return <details className="lp-report"><summary>รายงานเนื้อหาหรือคำถามผิด</summary><form onSubmit={e => { e.preventDefault(); const f = e.currentTarget; onReport(String(new FormData(f).get('issue'))); f.reset() }}><label>สิ่งที่ควรแก้ไข<textarea name="issue" rows={2} maxLength={2000} required /></label><button disabled={busy}>ส่งรายงาน</button></form></details>
}
