import { useState } from 'react'
import type { FormEvent } from 'react'
import { analyze, rpc } from './api'
import type { Snapshot } from './types'
import Icon from './Icons'
import { EmptyState, PageHeading, ProgressMeter, SectionHeading } from './ui'

type Props = { snapshot: Snapshot; busy: boolean; online: boolean; run: (action: () => Promise<void>) => Promise<void>; refresh: () => Promise<void>; open: (id: string) => void; initialCourse: string }
const statuses = { queued: 'รอวิเคราะห์', extracting: 'กำลังอ่านเอกสาร', analyzing: 'กำลังวิเคราะห์', ready: 'พร้อมเรียน', failed: 'วิเคราะห์ไม่สำเร็จ' }
export default function Library({ snapshot, busy, online, run, refresh, open, initialCourse }: Props) {
  const [query, setQuery] = useState('')
  const [courseFilter, setCourseFilter] = useState(initialCourse)
  const [adding, setAdding] = useState<'course' | 'material' | null>(null)
  const [source, setSource] = useState('')
  const [course, setCourse] = useState(initialCourse || snapshot.courses[0]?.id || '')
  const [deleteId, setDeleteId] = useState<string | null>(null)
  const [fileBusy, setFileBusy] = useState(false)
  const [importId, setImportId] = useState(() => crypto.randomUUID())
  const filtered = snapshot.materials.filter(m => (!courseFilter || m.course_id === courseFilter) && `${m.title} ${snapshot.courses.find(c => c.id === m.course_id)?.title || ''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))
  const createCourse = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault(); const form = e.currentTarget; const data = new FormData(form)
    void run(async () => { const id = await rpc<string>('lp_create_course', { p_title: data.get('title'), p_goal: data.get('goal'), p_target: data.get('date') || null }); setCourse(id); await refresh(); form.reset(); setAdding('material') })
  }
  const selectedCourse = snapshot.courses.find(c => c.id === courseFilter)
  return <><PageHeading eyebrow="YOUR PERSONAL KNOWLEDGE SPACE" title="เรียนสิ่งที่อยากเข้าใจ" description="รวมวิชา เอกสาร และบทเรียนของคุณไว้ในพื้นที่เดียว" action={<div className="lp-actions"><button className="lp-secondary" disabled={busy || !online} onClick={() => setAdding(adding === 'course' ? null : 'course')}>＋ สร้างวิชา</button><button disabled={busy || !online} onClick={() => setAdding(adding === 'material' ? null : snapshot.courses.length ? 'material' : 'course')}>＋ เพิ่มเนื้อหา</button></div>} />
    {adding && <section className="lp-card lp-import-panel"><div className="lp-section-title"><h2>{adding === 'course' ? 'เริ่มวิชาใหม่ของคุณ' : 'เพิ่มเนื้อหาให้ AI ช่วยสรุป'}</h2><button className="lp-secondary" disabled={busy} aria-label="ปิดฟอร์มเพิ่มเนื้อหา" onClick={() => setAdding(null)}>×</button></div>{adding === 'course' ? <form onSubmit={createCourse}><div className="lp-form-grid"><label>ชื่อวิชา<input name="title" maxLength={200} required placeholder="เช่น ชีววิทยา" autoFocus /></label><label>เป้าหมายที่อยากไปถึง<input name="goal" required placeholder="สิ่งที่อยากเข้าใจ" /></label><label>วันเป้าหมาย (ไม่บังคับ)<input name="date" type="date" /></label></div><button disabled={busy || !online}>สร้างวิชาและเพิ่มบทเรียน →</button></form> : <form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); void run(async () => { const id = await rpc<string>('lp_import', { p_course: course, p_title: data.get('title'), p_source: source, p_id: importId }); await refresh(); setAdding(null); setSource(''); setImportId(crypto.randomUUID()); open(id); await analyze(id); await refresh() }) }}><p>เลือกเอกสารหรือวางข้อความ ระบบจะสร้างสรุปและหัวข้อสำคัญสำหรับคุณ</p><div className="lp-grid"><label>วิชา<select value={course} required onChange={e => setCourse(e.target.value)}><option value="">เลือกวิชา</option>{snapshot.courses.map(c => <option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label>ชื่อบทเรียน<input name="title" maxLength={200} required placeholder="เช่น การแบ่งเซลล์" /></label></div><label className="lp-file-zone"><Icon name="library" /><strong>เพิ่ม PDF หรือไฟล์ข้อความ</strong><span>PDF ไม่เกิน 20 MB · TEXT UTF-8 ไม่เกิน 1 MB</span><input aria-label="เลือกเอกสาร PDF หรือ TEXT" type="file" accept="application/pdf,.pdf,text/plain,.txt" disabled={busy || fileBusy} onChange={e => { const file = e.target.files?.[0]; if (!file) return; setFileBusy(true); void run(async () => { try { if (file.name.toLowerCase().endsWith('.txt') || file.type === 'text/plain') { const { extractTextFile } = await import('./text-file'); setSource(await extractTextFile(file)) } else { const { extractPdf } = await import('./pdf'); setSource(await extractPdf(file)) } } finally { setFileBusy(false) } }) }} /></label>{fileBusy && <p role="status">กำลังอ่านไฟล์…</p>}<label>หรือวางเนื้อหาของคุณ<textarea value={source} onChange={e => setSource(e.target.value)} minLength={200} maxLength={100000} rows={6} required placeholder="วางข้อความอย่างน้อย 200 ตัวอักษร" /></label><div className="lp-row"><small>{source.length.toLocaleString()} / 100,000 ตัวอักษร · PDF ต้องเลือกข้อความได้</small><button disabled={busy || fileBusy || !online || !course}>บันทึกและวิเคราะห์ →</button></div></form>}</section>}
    {!courseFilter && snapshot.courses.length > 0 && <><SectionHeading title="วิชาของคุณ" caption={`${snapshot.courses.length} วิชา · เลือกวิชาเพื่อดูเส้นทางการเรียน`} /><div className="lp-course-grid">{snapshot.courses.map((c, i) => {
      const materials = snapshot.materials.filter(m => m.course_id === c.id)
      const activities = snapshot.plans.filter(p => p.course_id === c.id).flatMap(p => p.tasks)
      return <article className="lp-card lp-course-card" key={c.id}><div className={`lp-course-cover tone-${i % 3}`}><Icon name="library" /><span>{String(i + 1).padStart(2,'0')}</span></div><div className="lp-course-body"><span className="lp-muted">{materials.length} บทเรียน{c.target_date && ` · เป้าหมาย ${c.target_date}`}</span><h3>{c.title}</h3><p>{c.goal}</p><ProgressMeter label="กิจกรรมในวิชา" total={activities.length} value={activities.filter(t => t.status === 'completed').length} /><button className="lp-secondary" onClick={() => { setCourseFilter(c.id); setCourse(c.id) }}>เปิดวิชา <span>→</span></button></div></article>
    })}</div></>}
    <SectionHeading title={selectedCourse ? selectedCourse.title : 'บทเรียนและเอกสาร'} caption={selectedCourse?.goal} action={courseFilter ? <button className="lp-link" onClick={() => setCourseFilter('')}>← ดูทุกวิชา</button> : undefined} />
    {selectedCourse && <div className="lp-course-journey"><span><Icon name="library" /> {snapshot.materials.filter(m => m.course_id === courseFilter).length} บทเรียน</span><span><Icon name="plan" /> {selectedCourse.target_date ? `เป้าหมาย ${selectedCourse.target_date}` : 'เรียนตามจังหวะของคุณ'}</span></div>}
    <div className="lp-library-tools"><div className="lp-course-tabs" role="group" aria-label="กรองบทเรียนตามวิชา"><button aria-pressed={!courseFilter} className={!courseFilter ? 'active' : ''} onClick={() => setCourseFilter('')}>ทั้งหมด</button>{snapshot.courses.map(c => <button key={c.id} aria-pressed={courseFilter === c.id} className={courseFilter === c.id ? 'active' : ''} onClick={() => { setCourseFilter(c.id); setCourse(c.id) }}>{c.title}</button>)}</div><label className="lp-inline-search"><Icon name="search" /><input aria-label="ค้นหาเนื้อหาหรือวิชา" placeholder="ค้นหาบทเรียน…" value={query} onChange={e => setQuery(e.target.value)} /></label></div>
    <div className={courseFilter ? 'lp-learning-journey' : 'lp-grid'}>{filtered.length ? filtered.map((m, index) => {
      const tasks = snapshot.plans.flatMap(p => p.tasks).filter(t => t.content_id === m.id)
      const done = tasks.length > 0 && tasks.every(t => ['completed', 'skipped'].includes(t.status)) && tasks.some(t => t.status === 'completed')
      const resultCount = snapshot.attempts.filter(a => a.content_id === m.id && a.result).length
      return <article className="lp-card lp-material-card" key={m.id}>{courseFilter && <span className={`lp-journey-number ${done ? 'done' : ''}`}>{done ? <Icon name="check" /> : String(index + 1).padStart(2,'0')}</span>}<div className="lp-material-body"><div className="lp-row"><span className={`lp-tag ${m.status === 'failed' ? 'danger' : m.status !== 'ready' ? 'warning' : ''}`}>{done ? 'กิจกรรมเสร็จแล้ว' : statuses[m.status]}</span><small>{/\[PDF หน้า \d+\]/.test(m.source) ? 'PDF' : 'TEXT'}</small></div><small>{snapshot.courses.find(c => c.id === m.course_id)?.title}</small><h3>{m.title}</h3><p className="lp-clamp">{m.summary?.overview || (m.status === 'failed' ? 'เปิดบทเรียนเพื่อตรวจสอบและลองวิเคราะห์อีกครั้ง' : 'กำลังเตรียมสรุปและหัวข้อสำคัญสำหรับคุณ')}</p><div className="lp-material-meta"><span>{m.concepts.length} หัวข้อ</span>{resultCount > 0 && <span>ทดสอบแล้ว {resultCount} ครั้ง</span>}{tasks.length > 0 && <span>กิจกรรมสำเร็จ {tasks.filter(t => t.status === 'completed').length}/{tasks.length}</span>}</div><div className="lp-actions"><button className="lp-secondary" onClick={() => open(m.id)}>{m.status === 'ready' ? 'เปิดบทเรียน' : 'ดูสถานะ'} →</button><button className="lp-link lp-error" disabled={busy || !online} onClick={() => setDeleteId(m.id)}>ลบเนื้อหา</button></div>{deleteId === m.id && <div className="lp-alert error" role="alert"><strong>ลบเนื้อหานี้อย่างถาวร?</strong><p>ต้นฉบับ สรุป คำถาม ผลทดสอบ และกิจกรรมที่เกี่ยวข้องจะถูกลบด้วย</p><div className="lp-actions"><button className="lp-destructive" disabled={busy || !online} onClick={() => void run(async () => { await rpc('lp_delete_content', { p_content: m.id }); await refresh(); setDeleteId(null) })}>ยืนยันลบ</button><button className="lp-secondary" disabled={busy} onClick={() => setDeleteId(null)}>เก็บไว้ก่อน</button></div></div>}</div></article>
    }) : <EmptyState title={query ? 'ไม่พบบทเรียนที่ตรงกัน' : snapshot.courses.length ? 'วิชาพร้อมแล้ว เพิ่มบทเรียนแรกกัน' : 'เริ่มจากสิ่งที่คุณอยากเรียน'} text={query ? 'ลองเปลี่ยนคำค้น หรือเลือกดูทุกวิชา' : snapshot.courses.length ? 'เลือก PDF ไฟล์ข้อความ หรือวางเนื้อหาให้ผู้ช่วย AI สร้างสรุป' : 'สร้างวิชา ตั้งเป้าหมายเล็ก ๆ แล้วเพิ่มเอกสารสำหรับเรียน'} action={<button disabled={busy || !online} onClick={() => query ? setQuery('') : setAdding(snapshot.courses.length ? 'material' : 'course')}>{query ? 'ล้างคำค้น' : snapshot.courses.length ? 'เพิ่มบทเรียนแรก' : 'สร้างวิชาแรก'}</button>} />}</div>
    {snapshot.courses.length > 0 && <details className="lp-card lp-course-goals"><summary>จัดการเป้าหมายและวันเรียน</summary>{snapshot.courses.map(c => <form key={c.id} className="lp-course-goal-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); void run(async () => { await rpc('lp_course_edit', { p_course: c.id, p_goal: data.get('goal'), p_target: data.get('date') || null }); await refresh() }) }}><h3>{c.title}</h3><div className="lp-form-grid"><label>เป้าหมาย<input name="goal" defaultValue={c.goal} required /></label><label>วันเป้าหมาย<input name="date" type="date" defaultValue={c.target_date || ''} /></label></div><button className="lp-secondary" disabled={busy || !online}>บันทึกเป้าหมาย</button></form>)}</details>}
  </>
}
