import { useState } from 'react'
import type { Snapshot } from './types'
import { rpc } from './api'
import Icon from './Icons'
import { PageHeading } from './ui'

type Props = { snapshot: Snapshot; busy: boolean; online: boolean; run: (action: () => Promise<void>) => Promise<void>; refresh: () => Promise<void>; email: string; download: () => void; downloaded: boolean; clearDownload: () => void; install: (() => Promise<void>) | null; logout: () => void }
export default function Settings({ snapshot, busy, online, run, refresh, email, download, downloaded, clearDownload, install, logout }: Props) {
  const [days, setDays] = useState(snapshot.preferences.days)
  const [confirmLogout, setConfirmLogout] = useState(false)
  return <><PageHeading eyebrow="YOUR TIME, YOUR PACE" title="พื้นที่เรียนรู้ ที่พอดีกับคุณ" description="ปรับเวลา ภาษา และการใช้งานให้เข้ากับชีวิตประจำวัน" /><div className="lp-settings-layout"><form className="lp-card lp-settings-study" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); void run(async () => { await rpc('lp_preferences_save', { p_settings: { minutes: Number(data.get('minutes')), timezone: data.get('timezone'), days, language: data.get('language') } }); await refresh() }) }}><span className="lp-stat-icon"><Icon name="plan" /></span><h2>จังหวะการเรียนของคุณ</h2><p>เวลาน้อยก็เรียนได้ เลือกเวลาที่ทำได้อย่างสม่ำเสมอ</p><label>เวลาว่างต่อวัน (นาที)<input name="minutes" type="number" min={10} max={180} defaultValue={snapshot.preferences.minutes} required /></label><div className="lp-grid"><label>เขตเวลา<input name="timezone" defaultValue={snapshot.preferences.timezone} required /></label><label>ภาษาสำหรับการเรียน<select name="language" defaultValue={snapshot.preferences.language}><option value="th">ไทย</option><option value="en">English</option></select></label></div><fieldset><legend>วันที่สะดวกเรียน</legend><div className="lp-days">{['อา.','จ.','อ.','พ.','พฤ.','ศ.','ส.'].map((day,i) => <label key={day} className={days.includes(i) ? 'selected' : ''}><input type="checkbox" aria-label={`เรียนวัน${['อาทิตย์','จันทร์','อังคาร','พุธ','พฤหัสบดี','ศุกร์','เสาร์'][i]}`} checked={days.includes(i)} onChange={e => setDays(e.target.checked ? [...days,i] : days.filter(d => d !== i))} />{day}</label>)}</div></fieldset>{!days.length && <p className="lp-error" role="status">เลือกอย่างน้อยหนึ่งวันเพื่อจัดแผนการเรียน</p>}<p className="lp-muted">ปรับเวลาแล้ว ระบบจะจัดกิจกรรมที่ยังไม่เริ่มใหม่ โดยเก็บกิจกรรมที่เริ่มแล้วและล็อกไว้</p><button disabled={busy || !online || !days.length}>{busy ? 'กำลังบันทึก…' : 'บันทึกเวลาและปรับแผน'}</button>{!online && <p className="lp-muted">เชื่อมต่ออินเทอร์เน็ตเพื่อบันทึกการตั้งค่า</p>}</form>
    <aside><section className="lp-card"><span className="lp-stat-icon info"><Icon name="library" /></span><h2>พกบทเรียนไปด้วย</h2><p>เก็บสรุป ต้นฉบับ และแผนล่าสุดไว้บนอุปกรณ์ เพื่ออ่านได้แม้ไม่มีอินเทอร์เน็ต</p><span className={`lp-tag ${downloaded ? '' : 'info'}`}>{downloaded ? 'มีบทเรียนบนอุปกรณ์แล้ว' : 'ยังไม่ได้ดาวน์โหลด'}</span><div className="lp-actions"><button disabled={!online || busy} onClick={() => void run(async () => download())}>{downloaded ? 'อัปเดตบทเรียนที่บันทึก' : 'เก็บบทเรียนไว้บนอุปกรณ์'}</button></div>{downloaded && <button className="lp-link" disabled={busy} onClick={clearDownload}>ล้างบทเรียนบนอุปกรณ์</button>}<p className="lp-muted">การสร้าง AI และทำแบบทดสอบต้องออนไลน์ บทเรียนที่บันทึกอาจถูกล้างเมื่อพื้นที่อุปกรณ์ไม่พอ</p></section><section className="lp-card"><h2>LearnPilot บนหน้าจอของคุณ</h2><p>เปิดพื้นที่เรียนรู้ได้สะดวกเหมือนแอป</p>{install ? <button className="lp-secondary" onClick={() => void install()}>ติดตั้ง LearnPilot</button> : <p className="lp-muted">เลือก “ติดตั้งแอป” หรือ “เพิ่มไปยังหน้าจอโฮม” จากเมนูเบราว์เซอร์ หากอุปกรณ์รองรับ</p>}</section></aside></div>
    <section className="lp-card lp-settings-privacy"><div><span className="lp-eyebrow">YOUR ACCOUNT, YOUR CONTENT</span><h2>ข้อมูลการเรียนของคุณ</h2><p>{email}</p><p>เอกสารและผลการเรียนผูกกับบัญชีของคุณ เนื้อหาจะส่งให้ผู้ให้บริการ AI เมื่อคุณสั่งวิเคราะห์ ลบเอกสารและข้อมูลที่เกี่ยวข้องได้จากวิชาและเนื้อหา</p><p className="lp-muted">เมื่อออกจากระบบ บทเรียนที่ดาวน์โหลด โน้ต และกิจกรรมที่รอส่งบนอุปกรณ์จะถูกล้าง</p></div><div>{confirmLogout ? <><p role="status">ต้องการออกจากบัญชีนี้หรือไม่?</p><div className="lp-actions"><button disabled={busy} onClick={logout}>ยืนยันออกจากระบบ</button><button className="lp-secondary" disabled={busy} onClick={() => setConfirmLogout(false)}>ยกเลิก</button></div></> : <button className="lp-secondary" disabled={busy} onClick={() => setConfirmLogout(true)}>ออกจากระบบ</button>}</div></section>
  </>
}
