import { useState } from 'react'
import type { ReactNode } from 'react'
import type { Plan, Snapshot, Task } from './types'
import Icon from './Icons'
import { EmptyState, PageHeading, ProgressMeter, SectionHeading } from './ui'

type Activity = Task & { plan: Plan }
type Props = { snapshot: Snapshot; today: string; busy: boolean; online: boolean; settings: () => void; library: () => void; undo: (plan: Plan) => void; taskCard: (task: Activity) => ReactNode; history: (plan: Plan) => ReactNode }
export default function StudyPlanner({ snapshot, today, busy, online, settings, library, undo, taskCard, history }: Props) {
  const [filter, setFilter] = useState<'all' | 'todo' | 'completed'>('todo')
  const tasks = snapshot.plans.flatMap(plan => plan.tasks.map(task => ({ ...task, plan })))
  const filtered = tasks.filter(task => filter === 'all' || (filter === 'completed' ? task.status === 'completed' : ['pending','in_progress'].includes(task.status)))
  const dates = [...new Set(filtered.map(task => task.date || '9999'))].sort()
  const due = tasks.filter(task => task.date && task.date <= today && ['pending','in_progress'].includes(task.status))
  return <><PageHeading eyebrow="A LITTLE EVERY DAY" title="จัดเวลาวันนี้ ให้อนาคตของคุณ" description={`แผนที่พอดีกับวันละ ${snapshot.preferences.minutes} นาที · ${snapshot.preferences.timezone}`} action={<button className="lp-secondary" onClick={settings}><Icon name="settings" /> ปรับเวลาเรียน</button>} />
    <section className="lp-planner-overview"><div><span className="lp-tag">TODAY & NEXT</span><h2>{due.length ? `${due.length} กิจกรรมพร้อมให้คุณเริ่ม` : 'เรียนตามจังหวะที่เหมาะกับคุณ'}</h2><p>{due.length ? `วันนี้และงานค้างประมาณ ${due.reduce((sum, task) => sum + task.minutes, 0)} นาที เลือกทำทีละกิจกรรมได้เลย` : 'ทบทวนอย่างสม่ำเสมอ แล้วใช้แบบทดสอบค้นหาจุดที่ควรเรียนต่อ'}</p></div><div><ProgressMeter label="กิจกรรมที่ทำสำเร็จ" value={tasks.filter(t => t.status === 'completed').length} total={tasks.length} /><small>ความคืบหน้าของกิจกรรมแยกจากคะแนนความเข้าใจ</small></div></section>
    <div className="lp-plan-toolbar"><span><Icon name="plan" /> เส้นทางการเรียนของคุณ</span><div className="lp-filter-pills" role="group" aria-label="กรองสถานะกิจกรรม">{([['todo','ที่ต้องทำ'],['all','ทั้งหมด'],['completed','เสร็จแล้ว']] as const).map(([key,label]) => <button key={key} className={filter === key ? 'active' : ''} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label}</button>)}</div></div>
    {tasks.length ? dates.length ? <div className="lp-planner-timeline">{dates.map(date => <section className="lp-planner-day" key={date}><div className="lp-planner-day-heading"><span className={`lp-timeline-dot ${date <= today ? 'current' : ''}`} /><h2>{date === '9999' ? 'รอจัดเวลา' : date === today ? 'วันนี้' : date < today ? `ยังค้าง · ${new Date(`${date}T12:00:00`).toLocaleDateString('th-TH',{day:'numeric',month:'long'})}` : new Date(`${date}T12:00:00`).toLocaleDateString('th-TH',{weekday:'long',day:'numeric',month:'long'})}</h2><span className="lp-muted">{filtered.filter(t => (t.date || '9999') === date).length} กิจกรรม</span></div><div className="lp-task-list">{filtered.filter(t => (t.date || '9999') === date).map(t => <div key={t.id}><span className="lp-task-course">{snapshot.courses.find(c => c.id === t.plan.course_id)?.title}</span>{taskCard(t)}</div>)}</div></section>)}</div> : <EmptyState title={filter === 'completed' ? 'ทุกกิจกรรมที่ทำเสร็จ จะอยู่ตรงนี้' : 'ไม่มีกิจกรรมในหมวดนี้'} text="ลองเลือกดูทั้งหมด หรือกลับไปเรียนบทเรียนที่สนใจ" icon="plan" action={<button className="lp-secondary" onClick={() => setFilter('all')}>ดูกิจกรรมทั้งหมด</button>} /> : <EmptyState title="แผนเล็ก ๆ เริ่มจากความเข้าใจของคุณ" text="เพิ่มเนื้อหาและทำแบบทดสอบแรก ระบบจะจัดกิจกรรมให้พอดีกับเวลาว่าง" icon="plan" action={<button onClick={library}>เลือกบทเรียนเพื่อเริ่มต้น</button>} />}
    {snapshot.plans.length > 0 && <><SectionHeading title="แผนและเป้าหมายแต่ละวิชา" caption="ปรับแผนจากหลักฐานการเรียน โดยรักษากิจกรรมที่เริ่มแล้วและล็อกไว้" /><div className="lp-grid">{snapshot.plans.map(plan => <section className="lp-card lp-plan-details" key={plan.id}><span className="lp-eyebrow">แผนเวอร์ชัน {plan.version}</span><h3>{snapshot.courses.find(c => c.id === plan.course_id)?.title}</h3><ProgressMeter label="กิจกรรมในวิชา" value={plan.tasks.filter(t => t.status === 'completed').length} total={plan.tasks.length} /><p>{plan.reason}</p>{plan.tasks.some(t => !t.date) && <p className="lp-planner-warning">มี {plan.tasks.filter(t => !t.date).length} กิจกรรมรอจัดเวลา ลองเพิ่มเวลาว่าง</p>}<details><summary>ประวัติการปรับแผน</summary>{history(plan)}</details><button className="lp-link" disabled={busy || !online || plan.version === 1} onClick={() => undo(plan)}>ย้อนกลับแผนก่อนหน้า</button></section>)}</div></>}
  </>
}
