import { useState } from 'react'
import type { ReactNode } from 'react'
import type { Material, Snapshot, Task, Plan } from './types'
import type { NavigationPage } from './navigation-items'
import Icon from './Icons'
import { EmptyState, PageHeading, ProgressMeter, SectionHeading } from './ui'

type Activity = Task & { plan: Plan }
type DashboardProps = { snapshot: Snapshot; due: Activity[]; completed: number; tasks: Activity[]; navigate: (page: NavigationPage) => void; open: (id: string) => void; taskCard: (task: Activity) => ReactNode; name: string }
export function Dashboard({ snapshot, due, completed, tasks, navigate, open, taskCard, name }: DashboardProps) {
  const ready = snapshot.materials.filter(material => material.status === 'ready')
  const next = due[0] && snapshot.materials.find(material => material.id === due[0].content_id && material.status === 'ready') || ready[0]
  const drafts = snapshot.attempts.filter(attempt => !attempt.result)
  return <>
    <PageHeading eyebrow={new Date().toLocaleDateString('th-TH', { timeZone: snapshot.preferences.timezone, weekday: 'long', day: 'numeric', month: 'long' })} title={`สวัสดี ${name || 'ผู้เรียน'} 🌿`} description="พื้นที่เล็ก ๆ สำหรับการเรียนรู้ที่เติบโตได้ทุกวัน" action={<button className="lp-secondary" onClick={() => navigate('library')}>＋ เพิ่มเนื้อหา</button>} />
    <div className="lp-home-layout"><section className="lp-welcome-panel"><span className="lp-tag">YOUR NEXT SMALL STEP</span><h2>{next ? 'พร้อมเรียนต่ออีกนิดไหม?' : 'เปลี่ยนเนื้อหาของคุณให้เป็นความเข้าใจ'}</h2><p>{next ? `กลับมาทบทวน ${next.title} แล้วตรวจสอบความเข้าใจในจังหวะของคุณ` : 'เพิ่มเอกสาร ให้ AI ช่วยจัดสรุป แล้วค้นหาวิธีเรียนที่เหมาะกับคุณ'}</p><button onClick={() => next ? open(next.id) : navigate('library')}>{next ? 'เรียนต่อ' : 'เริ่มสร้างวิชาแรก'} <span aria-hidden="true">→</span></button><div className="lp-welcome-art" aria-hidden="true"><span className="lp-art-ring" /><Icon name="compass" /><span className="lp-art-leaf" /><i>Learn at your own pace.</i></div></section>
    <section className="lp-card lp-daily-overview"><span className="lp-eyebrow">MY LEARNING</span><h2>ทีละก้าว ในทุกวัน</h2><div className="lp-mini-stat"><span><Icon name="clock" /> เวลาเรียนที่ตั้งไว้</span><strong>{snapshot.preferences.minutes}<small> นาที/วัน</small></strong></div><div className="lp-mini-stat"><span><Icon name="quiz" /> แบบทดสอบที่ส่ง</span><strong>{snapshot.attempts.filter(a => a.result).length}<small> ครั้ง</small></strong></div><ProgressMeter label="กิจกรรมที่ทำสำเร็จ" value={completed} total={tasks.length} /><button className="lp-link" onClick={() => navigate('progress')}>ดูผลการเรียนรู้ →</button></section></div>
    {drafts.length > 0 && <div className="lp-alert"><Icon name="quiz" /> มีแบบทดสอบที่ยังทำไม่เสร็จ {drafts.length} ชุด <button className="lp-link" onClick={() => open(drafts[0].content_id)}>กลับไปทำต่อ →</button></div>}
    <div className="lp-home-lower"><section><SectionHeading title="สิ่งที่ควรทำต่อ" caption={due.length ? `${due.length} กิจกรรมวันนี้และงานที่ยังค้าง` : 'เริ่มจากเนื้อหาที่อยากเข้าใจ'} action={<button className="lp-link" onClick={() => navigate('plan')}>ดูแผน →</button>} /><div className="lp-task-list">{due.length ? due.slice(0, 2).map(taskCard) : <EmptyState title="วันนี้มีพื้นที่ให้เริ่มต้นใหม่" text={ready.length ? 'เลือกบทเรียนเพื่อทบทวนหรือทำแบบทดสอบ แล้วระบบจะจัดแผนให้คุณ' : 'เพิ่มเนื้อหาและทำแบบทดสอบแรก เพื่อให้ระบบช่วยวางแผนการเรียน'} action={<button className="lp-secondary" onClick={() => navigate('library')}>เปิดวิชาและเนื้อหา</button>} icon="plan" />}</div></section><aside><SectionHeading title="เรียนรู้ด้วย AI" /><section className="lp-card lp-ai-shortcut"><span className="lp-ai-avatar"><Icon name="tutor" /></span><h3>เนื้อหายาก ค่อย ๆ เข้าใจได้</h3><p>อ่านสรุป ทบทวนหัวข้อสำคัญ และสร้างแบบทดสอบจากเอกสารของคุณ</p><button className="lp-secondary" onClick={() => navigate('tutor')}>เปิดผู้ช่วยการเรียนรู้ <span aria-hidden="true">↗</span></button></section>{ready.length > 0 && <><SectionHeading title="เนื้อหาพร้อมเรียน" /><div className="lp-compact-lessons">{ready.slice(0, 3).map(m => <button key={m.id} className="lp-lesson-row" onClick={() => open(m.id)}><span className="lp-lesson-glyph"><Icon name="library" /></span><span><strong>{m.title}</strong><small>{snapshot.courses.find(c => c.id === m.course_id)?.title}</small></span><span aria-hidden="true">→</span></button>)}</div></>}</aside></div>
  </>
}

export function Analytics({ snapshot, completed, navigate, openAttempt }: { snapshot: Snapshot; completed: number; navigate: (page: NavigationPage) => void; openAttempt: (content: string, attempt: string) => void }) {
  const finished = snapshot.attempts.filter(a => a.result)
  const total = finished.reduce((sum, a) => sum + a.result!.total, 0)
  const correct = finished.reduce((sum, a) => sum + a.result!.score, 0)
  return <><PageHeading eyebrow="GROW AT YOUR OWN PACE" title="ทุกก้าวของการเรียนรู้" description="เห็นสิ่งที่เข้าใจ และรู้ว่าควรกลับไปทบทวนอะไร" /><div className="lp-analytics-stats"><div className="lp-card"><span className="lp-stat-icon"><Icon name="library" /></span><span>วิชาของคุณ</span><strong>{snapshot.courses.length}</strong></div><div className="lp-card"><span className="lp-stat-icon info"><Icon name="quiz" /></span><span>แบบทดสอบที่ส่ง</span><strong>{finished.length}</strong></div><div className="lp-card"><span className="lp-stat-icon amber"><Icon name="check" /></span><span>กิจกรรมที่เสร็จ</span><strong>{completed}</strong></div></div>
    <SectionHeading title="ความเข้าใจในแต่ละหัวข้อ" caption="อ้างอิงคำถามไม่ซ้ำจากแบบทดสอบล่าสุด 3 ครั้งของเนื้อหาเวอร์ชันเดียวกัน" />
    <div className="lp-grid">{snapshot.evidence.length ? snapshot.evidence.map(e => <article className="lp-card lp-evidence" key={e.id}><div className="lp-row"><span className={`lp-tag ${e.sample < 3 ? 'warning' : e.correct / e.sample < .6 ? 'danger' : ''}`}>{e.sample < 3 ? 'กำลังเก็บหลักฐาน' : e.status}</span><strong>{e.sample >= 3 ? `${Math.round(e.correct / e.sample * 100)}%` : '—'}</strong></div><h3>{e.name}</h3><ProgressMeter label={`ตอบถูก ${e.correct} จาก ${e.sample} ข้อ`} value={e.correct} total={e.sample} /><p className="lp-muted">{e.sample < 3 ? 'ต้องมีหลักฐานอย่างน้อย 3 ข้อเพื่อช่วยประเมินหัวข้อนี้' : e.correct / e.sample < .6 ? 'ลองกลับไปอ่านสรุป แล้วทำแบบทดสอบใหม่' : 'รักษาความเข้าใจด้วยการทบทวนตามแผน'}</p></article>) : <EmptyState title="ความเข้าใจ เริ่มวัดได้จากการลองทำ" text="ทำแบบทดสอบจากบทเรียน แล้วคุณจะเห็นหัวข้อที่เข้าใจและหัวข้อที่ควรทบทวน" icon="progress" action={<button onClick={() => navigate('library')}>เลือกบทเรียนเพื่อทดสอบ</button>} />}</div>
    <SectionHeading title="บันทึกการทดสอบ" caption={total ? `คำตอบที่ถูกสะสม ${correct} / ${total} ข้อ · แต่ละชุดมีความยากต่างกัน จึงไม่ใช้คะแนนรวมสรุปพัฒนาการ` : 'ผลทดสอบจะแสดงที่นี่หลังส่งคำตอบ'} />
    {finished.length ? <div className="lp-history-list">{finished.slice().sort((a,b) => b.created_at.localeCompare(a.created_at)).map(a => <button className="lp-card lp-attempt" key={a.id} onClick={() => openAttempt(a.content_id, a.id)}><span className="lp-stat-icon info"><Icon name="quiz" /></span><span>{snapshot.materials.find(m => m.id === a.content_id)?.title || 'แบบทดสอบ'}<small>{new Date(a.created_at).toLocaleString('th-TH', { timeZone: snapshot.preferences.timezone })}</small></span><strong>{a.result!.score}<small> / {a.result!.total}</small></strong><span aria-hidden="true">→</span></button>)}</div> : <EmptyState title="ยังไม่มีแบบทดสอบที่ส่ง" text="คะแนนและคำอธิบายจะปรากฏเมื่อคุณทำแบบทดสอบครบและส่งคำตอบ" />}
    <p className="lp-muted">กิจกรรมที่เสร็จและคะแนนความเข้าใจเป็นคนละตัวชี้วัด ผลทดสอบยังไม่ใช่หลักฐานการจำระยะยาว</p></>
}

export function SearchPage({ userId, snapshot, open, openAttempt, openCourse, navigate }: { userId: string; snapshot: Snapshot; open: (id: string) => void; openAttempt: (content: string, attempt: string) => void; openCourse: (id: string) => void; navigate: (page: NavigationPage) => void }) {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('all')
  const historyKey = 'leanpilot:' + userId + ':searches'
  const [recent, setRecent] = useState<string[]>(() => { try { const values: unknown = JSON.parse(localStorage.getItem(historyKey) || '[]'); return Array.isArray(values) ? values.filter((value): value is string => typeof value === 'string').slice(0, 5) : [] } catch { return [] } })
  const normalized = query.trim().toLocaleLowerCase()
  const matches = (value: string) => value.toLocaleLowerCase().includes(normalized)
  const courses = snapshot.courses.filter(c => matches(`${c.title} ${c.goal}`))
  const materials = snapshot.materials.filter(m => matches(`${m.title} ${m.summary?.overview || ''} ${m.concepts.map(c => c.name).join(' ')}`))
  const quizzes = snapshot.attempts.filter(a => {
    const material = snapshot.materials.find(m => m.id === a.content_id)
    const course = snapshot.courses.find(c => c.id === material?.course_id)
    return matches(`${course?.title || ''} ${material?.title || ''} ${a.questions.map(q => q.prompt).join(' ')}`)
  })
  const remember = () => { if (query.trim()) { const next = [query.trim(), ...recent.filter(value => value !== query.trim())].slice(0, 5); setRecent(next); try { localStorage.setItem(historyKey, JSON.stringify(next)) } catch { /* Search still works without local storage. */ } } }
  const count = (category === 'all' || category === 'courses' ? courses.length : 0) + (category === 'all' || category === 'materials' ? materials.length : 0) + (category === 'all' || category === 'quiz' ? quizzes.length : 0)
  return <><PageHeading eyebrow="FIND YOUR NEXT INSIGHT" title="ทุกสิ่งที่อยากเรียน อยู่ใกล้แค่ค้นหา" description="ค้นหาวิชา เนื้อหา หัวข้อในบทเรียน และแบบทดสอบของคุณ" /><form className="lp-search-box" role="search" onSubmit={e => { e.preventDefault(); remember() }}><Icon name="search" /><input autoFocus aria-label="ค้นหาทั้งพื้นที่เรียนรู้" value={query} onChange={e => setQuery(e.target.value)} placeholder="อยากเรียนรู้อะไรวันนี้?" /><button>ค้นหา</button></form>
    <div className="lp-filter-pills" role="group" aria-label="ประเภทผลการค้นหา">{[['all','ทั้งหมด'],['courses','วิชา'],['materials','เนื้อหา'],['quiz','แบบทดสอบ']].map(([key, label]) => <button key={key} aria-pressed={category === key} className={category === key ? 'active' : ''} onClick={() => setCategory(key)}>{label}</button>)}</div>
    {!normalized ? <><SectionHeading title="ลองเริ่มจากวิชาของคุณ" /><div className="lp-suggestion-chips">{snapshot.courses.map(c => <button className="lp-secondary" key={c.id} onClick={() => setQuery(c.title)}><Icon name="search" />{c.title}</button>)}</div>{recent.length > 0 && <><SectionHeading title="คำค้นล่าสุดบนอุปกรณ์นี้" /><div className="lp-suggestion-chips">{recent.map(value => <button className="lp-secondary" key={value} onClick={() => setQuery(value)}>{value}</button>)}</div></>}{!snapshot.courses.length && <EmptyState title="เพิ่มเนื้อหา เพื่อเริ่มค้นพบ" text="เมื่อมีวิชาและเอกสาร คุณจะค้นหาได้จากชื่อและเนื้อหาสรุปของคุณ" icon="search" action={<button onClick={() => navigate('library')}>สร้างวิชาแรก</button>} />}</> : <><SectionHeading title={`พบ ${count} รายการ`} />{count === 0 && <EmptyState title="ยังไม่พบสิ่งที่คุณค้นหา" text="ลองใช้คำสั้นลง เปลี่ยนประเภท หรือค้นหาด้วยชื่อวิชา" icon="search" action={<button className="lp-secondary" onClick={() => { setQuery(''); setCategory('all') }}>เริ่มค้นหาใหม่</button>} />}{(category === 'all' || category === 'courses') && courses.length > 0 && <section><h2>วิชา</h2>{courses.map(c => <button className="lp-search-result" key={c.id} onClick={() => { remember(); openCourse(c.id) }}><span className="lp-stat-icon"><Icon name="library" /></span><span><strong>{c.title}</strong><small>{c.goal}</small></span><span>→</span></button>)}</section>}{(category === 'all' || category === 'materials') && materials.length > 0 && <section><h2>เนื้อหา</h2>{materials.map(m => <button className="lp-search-result" key={m.id} onClick={() => { remember(); open(m.id) }}><span className="lp-stat-icon info"><Icon name="library" /></span><span><strong>{m.title}</strong><small>{m.summary?.overview || 'เนื้อหาที่คุณเพิ่ม'}</small></span><span>→</span></button>)}</section>}{(category === 'all' || category === 'quiz') && quizzes.length > 0 && <section><h2>แบบทดสอบ</h2>{quizzes.map(a => <button className="lp-search-result" key={a.id} onClick={() => { remember(); openAttempt(a.content_id, a.id) }}><span className="lp-stat-icon amber"><Icon name="quiz" /></span><span><strong>{snapshot.materials.find(m => m.id === a.content_id)?.title}</strong><small>{a.result ? `ตอบถูก ${a.result.score} / ${a.result.total}` : 'ยังทำไม่เสร็จ'} · {a.questions.length} ข้อ</small></span><span>→</span></button>)}</section>}</>}
  </>
}

export function TutorPanel({ material, startQuiz, busy, online }: { material: Material; startQuiz: () => void; busy: boolean; online: boolean }) {
  const [mode, setMode] = useState<'summary' | 'concepts' | 'remember'>('summary')
  return <section className="lp-tutor-panel"><div className="lp-tutor-intro"><span className="lp-ai-avatar"><Icon name="tutor" /></span><div><strong>ผู้ช่วยการเรียนรู้</strong><small>อ้างอิงสรุป AI ของบทเรียนนี้</small></div><span className="lp-tag">AI</span></div><div className="lp-tutor-context"><Icon name="library" /><span>{material.title}</span></div><p className="lp-muted">เลือกสิ่งที่อยากทบทวน คำอธิบายมาจากผลวิเคราะห์เอกสารของคุณ</p><div className="lp-ai-actions" role="group" aria-label="เลือกวิธีทบทวน">{([['summary','สรุปบทนี้'],['concepts','ทบทวนหัวข้อ'],['remember','สิ่งที่ควรจำ']] as const).map(([key,label]) => <button className={mode === key ? 'active' : ''} aria-pressed={mode === key} key={key} onClick={() => setMode(key)}>{label}</button>)}</div><div className="lp-tutor-response" aria-live="polite" key={mode}><span className="lp-eyebrow">จากเอกสารของคุณ</span>{mode === 'summary' ? <p>{material.summary?.overview || 'ยังไม่มีสรุปภาพรวม'}</p> : mode === 'concepts' ? material.concepts.map(c => <details key={c.id}><summary>{c.name}</summary><p>{c.description}</p></details>) : material.summary?.points.length ? <ul>{material.summary.points.map((p,i) => <li key={i}>{p.text}</li>)}</ul> : <p>ยังไม่มีประเด็นสำหรับทบทวน</p>}</div><button disabled={busy || !online || !material.concepts.length} onClick={startQuiz}><Icon name="quiz" /> สร้างแบบทดสอบ</button><p className="lp-muted">ตรวจความเข้าใจด้วยคำถามจากบทเรียนนี้</p></section>
}
export function TutorPage({ snapshot, initialMaterial, onChoose, startQuiz, busy, online, navigate }: { snapshot: Snapshot; initialMaterial: string | null; onChoose: (id: string) => void; startQuiz: (material: Material) => void; busy: boolean; online: boolean; navigate: (page: NavigationPage) => void }) {
  const ready = snapshot.materials.filter(m => m.status === 'ready')
  const material = ready.find(m => m.id === initialMaterial) || ready[0]
  return <><PageHeading eyebrow="YOUR AI LEARNING COMPANION" title="ค่อย ๆ เข้าใจ ไปด้วยกัน" description="ให้สรุป AI ช่วยพาคุณกลับไปทบทวนสิ่งสำคัญจากบทเรียน" />{material ? <div className="lp-tutor-layout"><aside className="lp-card"><h2>เลือกบทเรียน</h2><p className="lp-muted">ผู้ช่วยจะใช้บริบทของบทเรียนที่คุณเลือก</p><div className="lp-compact-lessons">{ready.map(m => <button className={`lp-lesson-row ${material.id === m.id ? 'active' : ''}`} key={m.id} aria-pressed={material.id === m.id} onClick={() => onChoose(m.id)}><Icon name="library" /><span><strong>{m.title}</strong><small>{snapshot.courses.find(c => c.id === m.course_id)?.title}</small></span></button>)}</div></aside><TutorPanel key={material.id} material={material} busy={busy} online={online} startQuiz={() => startQuiz(material)} /></div> : <EmptyState title="ให้ผู้ช่วยได้รู้จักบทเรียนของคุณก่อน" text="เพิ่มเอกสารและวิเคราะห์เนื้อหา แล้วกลับมาอ่านสรุป ทบทวนหัวข้อ และสร้างแบบทดสอบได้ที่นี่" icon="compass" action={<button onClick={() => navigate('library')}>เพิ่มเนื้อหาสำหรับเรียน</button>} />}</>
}
